title: Sai Prasanna Portfolio
author: Gutta Sai Prasanna
email: guttasaiprasanna7485@gmail.com
description: >- 
  AI/ML Enthusiast | B.Tech in CSE (AI & DS) | Python | Data Science 
github_username: saiprasanna04
theme: minima
